# Keras Basic
### * Sequential Layer 의 주요 레이어 정리 
#### [1]  Dense Layer : Fully Connected Layer, layer의 입력과 출력 사이에 있는 모든 뉴런이 서로 연결 되는 Layer
#### [2]  Flatten Layer : 다차원(4차원)을 2차원으로 축소하여 FC Layer에 전달한다
#### [3]  Conv2D Layer : 이미지 특징을 추출하는 Convolution Layer 
#### [4]  MaxPool2D Layer : 중요 데이터(값이 큰 데이터)를 subsampling 하는 Layer
#### [5]  Dropout Layer : 학습시 신경망의 과적합을 막기위해 일부 뉴런을 제거하는 Layer

#### https://greeksharifa.github.io/keras/2018/06/29/Keras-Tutorial/

### [1] Dense Layer

In [1]:
# keras_basic

import tensorflow as tf
import numpy as np

In [2]:
# keras 를 이용한 XOR 네트워크
x_data = [[0,0],
          [0,1],
          [1,0],
          [1,1]]    # (4,2)

y_data = [[0],
          [1],
          [1],
          [0]]      # (4,1)

In [3]:
model = tf.keras.Sequential([
    #  (4,2) * (2,2) = (4,2)
    # units : 뉴런의 갯수
    # Param : 6 (W:4, b:2), W = W의 shape 값의 곱, b = W의 컬럼의 갯수(2차원인 경우) 
    # 파라미터수: (입력측 뉴런의 수 + 1) * (출력측 뉴런의 수) = (2 + 1) * 2 = 6
    tf.keras.layers.Dense(units=2,activation='sigmoid',input_shape=(2,)),
    
    #  (4,2) * (2,1)  = (4,1)
    # Param : 3 (W:2, b:1), W = W의 shape 값의 곱, b = W의 컬럼의 갯수(2차원인 경우) 
    # 파라미터수:  (입력측 뉴런의 수 + 1) * (출력측 뉴런의 수) = (2 + 1) * 1 = 3
    tf.keras.layers.Dense(units=1,activation='sigmoid')
])

model.compile(optimizer=tf.keras.optimizers.Adam(lr=0.1),loss='mse',metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 2)                 6         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 3         
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [4]:
model.fit(x_data,y_data,epochs=250,batch_size=1,verbose=1) # verbose=1, 메세지를 출력

Train on 4 samples
Epoch 1/250
4/4 [==============================] - 1s 135ms/sample - loss: 0.3008 - accuracy: 0.5000
Epoch 2/250
4/4 [==============================] - 0s 3ms/sample - loss: 0.2769 - accuracy: 0.5000
Epoch 3/250
4/4 [==============================] - 0s 5ms/sample - loss: 0.2817 - accuracy: 0.2500
Epoch 4/250
4/4 [==============================] - 0s 3ms/sample - loss: 0.2567 - accuracy: 0.2500
Epoch 5/250
4/4 [==============================] - 0s 2ms/sample - loss: 0.2563 - accuracy: 0.5000
Epoch 6/250
4/4 [==============================] - 0s 2ms/sample - loss: 0.2614 - accuracy: 0.5000
Epoch 7/250
4/4 [==============================] - 0s 2ms/sample - loss: 0.2659 - accuracy: 0.5000
Epoch 8/250
4/4 [==============================] - 0s 3ms/sample - loss: 0.2568 - accuracy: 0.5000
Epoch 9/250
4/4 [==============================] - 0s 2ms/sample - loss: 0.2627 - accuracy: 0.5000
Epoch 10/250
4/4 [==============================] - 0s 3ms/sample - loss: 0.2528 - accur

4/4 [==============================] - 0s 3ms/sample - loss: 0.0090 - accuracy: 1.0000
Epoch 164/250
4/4 [==============================] - 0s 2ms/sample - loss: 0.0089 - accuracy: 1.0000
Epoch 165/250
4/4 [==============================] - 0s 2ms/sample - loss: 0.0088 - accuracy: 1.0000
Epoch 166/250
4/4 [==============================] - 0s 5ms/sample - loss: 0.0086 - accuracy: 1.0000
Epoch 167/250
4/4 [==============================] - 0s 2ms/sample - loss: 0.0084 - accuracy: 1.0000
Epoch 168/250
4/4 [==============================] - 0s 3ms/sample - loss: 0.0083 - accuracy: 1.0000
Epoch 169/250
4/4 [==============================] - 0s 3ms/sample - loss: 0.0082 - accuracy: 1.0000
Epoch 170/250
4/4 [==============================] - 0s 3ms/sample - loss: 0.0081 - accuracy: 1.0000
Epoch 171/250
4/4 [==============================] - 0s 2ms/sample - loss: 0.0079 - accuracy: 1.0000
Epoch 172/250
4/4 [==============================] - 0s 3ms/sample - loss: 0.0078 - accuracy: 1.0000
Epoc

In [5]:
preds = model.predict(x_data)
np.round(preds)

array([[0.],
       [1.],
       [1.],
       [0.]], dtype=float32)

In [6]:
model.evaluate(x_data,y_data)
# [0.00010443033534102142, 1.0]

4/1 [========================================================================================================================] - 0s 15ms/sample - loss: 0.0031 - accuracy: 1.0000


[0.0030605620704591274, 1.0]

In [7]:
# X,Y input data 
x_train = np.array([[1.0,   2.0,  3.0,  4.0,  5.0],
                    [6.0,   7.0,  8.0,  9.0, 10.0],
                    [11.0, 12.0, 13.0, 14.0, 15.0]])  # (3,5)
                    
                    
y_train = np.array([[1.1,   2.2,  3.3,  4.4,  5.5],
                    [6.1,   7.2,  8.3,  9.4, 10.5],
                    [11.1, 12.2, 13.3, 14.4, 15.5]]) # (3,5)

model = tf.keras.Sequential([
    # (3,1) * (1,100) = (3,100)   , Param :200 (W:1*100, b:100), (1 + 1) * 100 = 200
    # tf.keras.layers.Dense(units=100, activation='relu', input_shape=(1,)), # input data의 shape을 (?,1) 

    # (3,5) * (5,100) = (3,100)   , Param :600 (W:5*100, b:100), (5 + 1) * (100) = 600
    tf.keras.layers.Dense(units=100, activation='relu', input_shape=(5,)), # input data의 shape을 (?,5) 

    
    # (3,100) * (100,50) = (3,50)   , Param : 5050 (W:100*50, b:50), (100+1)*50 = 5050
    tf.keras.layers.Dense(units=50, activation='relu' ), 
    
    # (3,50) * (50,25) = (3,25)   , Param : 1275 (W:50*25, b:25), (50 + 1)* 25 = 1275
    tf.keras.layers.Dense(units=25, activation='relu' ),
    
    # (3,25) * (25,5) = (3,5)   , Param : 130 (W:25*5, b:5), (25 + 1) * 5 = 130
    tf.keras.layers.Dense(units=5 , activation='relu' ),
    
#     # (3,5) * (5,1) = (3,1)   , Pram : 6  (W:5*1, b:1), (5 + 1) *1 = 6
#     tf.keras.layers.Dense(units=1)
])

model.compile(optimizer=tf.keras.optimizers.Adam(lr=0.01), loss='mse')

model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 100)               600       
_________________________________________________________________
dense_3 (Dense)              (None, 50)                5050      
_________________________________________________________________
dense_4 (Dense)              (None, 25)                1275      
_________________________________________________________________
dense_5 (Dense)              (None, 5)                 130       
Total params: 7,055
Trainable params: 7,055
Non-trainable params: 0
_________________________________________________________________


In [8]:
model.fit(x_train, y_train, epochs=100)

Train on 3 samples
Epoch 1/100
3/3 [==============================] - 0s 121ms/sample - loss: 68.7435
Epoch 2/100
3/3 [==============================] - 0s 665us/sample - loss: 35.9291
Epoch 3/100
3/3 [==============================] - 0s 680us/sample - loss: 37.6563
Epoch 4/100
3/3 [==============================] - 0s 666us/sample - loss: 27.6438
Epoch 5/100
3/3 [==============================] - 0s 666us/sample - loss: 17.2133
Epoch 6/100
3/3 [==============================] - 0s 997us/sample - loss: 12.0474
Epoch 7/100
3/3 [==============================] - 0s 665us/sample - loss: 7.7417
Epoch 8/100
3/3 [==============================] - 0s 665us/sample - loss: 4.4820
Epoch 9/100
3/3 [==============================] - 0s 998us/sample - loss: 3.9165
Epoch 10/100
3/3 [==============================] - 0s 665us/sample - loss: 4.8520
Epoch 11/100
3/3 [==============================] - 0s 332us/sample - loss: 4.0756
Epoch 12/100
3/3 [==============================] - 0s 983us/sample - l

Epoch 100/100
3/3 [==============================] - 0s 665us/sample - loss: 5.9482e-04


In [9]:
model.predict(x_train)

array([[ 1.1283075,  2.1880012,  3.3120499,  4.453049 ,  5.4993   ],
       [ 6.0847797,  7.2178354,  8.329954 ,  9.4084635, 10.463485 ],
       [11.119369 , 12.2074   , 13.301576 , 14.377923 , 15.535123 ]],
      dtype=float32)

In [10]:
model.evaluate(x_train,y_train)

3/1 [==========================================================================================] - 0s 20ms/sample - loss: 5.9404e-04


0.000594036711845547

 ### [2] Flatten Layer

In [11]:
# 4차원 데이터를 2차원으로 축소하여 FC Layer에 전달
data = np.arange(1000*28*28*10).reshape(1000,28,28,10).astype(np.float32)
print(data.shape) # (None, 28, 28, 10)
layer = tf.keras.layers.Flatten()
outputs = layer(data)
print(outputs.shape) # (None, 28*28*10) = (None,7840)

(1000, 28, 28, 10)
(1000, 7840)


In [12]:
# 3차원 데이터를 2차원으로 축소하여 FC Layer에 전달
data = np.arange(1000*28*28).reshape(1000,28,28).astype(np.float32)
print(data.shape) # (None, 28, 28)
layer = tf.keras.layers.Flatten()
outputs = layer(data)
print(outputs.shape) # (None, 28*28) = (None,784)

(1000, 28, 28)
(1000, 784)


In [13]:
# 2차원 데이터는 그대로 FC Layer에 전달
data = np.arange(28*28).reshape(28,28).astype(np.float32)
print(data.shape) # (28, 28)
layer = tf.keras.layers.Flatten()
outputs = layer(data)
print(outputs.shape) # (28,28) 

(28, 28)
(28, 28)


### [3] Dropout Layer

In [14]:
# https://www.tensorflow.org/api_docs/python/tf/keras/layers/Dropout
# The Dropout layer randomly sets input units to 0 with a frequency of rate 
# at each step during training time, which helps prevent overfitting. 
# Inputs not set to 0 are scaled up by 1/(1 - rate) such that the sum over all inputs is unchanged.

# Note that the Dropout layer only applies when training is set to True such that
# no values are dropped during inference. When using model.fit, training will be
# appropriately set to True automatically, and in other contexts, you can set 
# the kwarg explicitly to True when calling the layer.

# (This is in contrast to setting trainable=False for a Dropout layer.
# trainable does not affect the layer's behavior, as Dropout does not have any 
# variables/weights that can be frozen during training.)

In [32]:
# 신버전 keras dropout
tf.random.set_seed(0)

data = np.arange(10).reshape(5,2).astype(np.float32)
layer = tf.keras.layers.Dropout(0.3,input_shape=(2,))  # 0.3 : 30% dropout
outputs = layer(data,training=True)
 # model.fit()호출 시는  학습 모드로 training=True가 되어 dropuout 적용
 # model.evaluate() 호출 시는 예측 모드로 False가 되어 dropuout이 수행되지 않음
print(outputs.numpy())
print(data * 1 /(1 - 0.3))

[[ 0.         0.       ]
 [ 2.857143   4.285714 ]
 [ 5.714286   7.1428576]
 [ 8.571428  10.       ]
 [11.428572   0.       ]]
[[ 0.         1.4285715]
 [ 2.857143   4.285714 ]
 [ 5.714286   7.142857 ]
 [ 8.571428  10.       ]
 [11.428572  12.857143 ]]


In [34]:
# 구버전 dropout , 사용하기 번거로움!
tf.random.set_seed(0)

data = np.arange(10).reshape(5,2).astype(np.float32)

def layer1(X,dr_rate):
    return tf.nn.dropout(X,rate=dr_rate)

print(layer1(data,dr_rate= 0.3))

tf.Tensor(
[[ 0.         0.       ]
 [ 2.857143   4.285714 ]
 [ 5.714286   7.1428576]
 [ 8.571428  10.       ]
 [11.428572   0.       ]], shape=(5, 2), dtype=float32)
