## RNN(Recurrent Neural Network) : 순환 신경망
#### 순서가 있는 시퀀스 데이터, time series data(시계열 데이터)를 입력하여 예측

In [1]:
# rnn_basic
import numpy as np
import tensorflow as tf

### One cell: 4 (input_dim) in 2 (hidden_size)

![image](https://cloud.githubusercontent.com/assets/901975/23348727/cc981856-fce7-11e6-83ea-4b187473466b.png)

In [2]:
# One hot encoding for each char in 'hello'
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]

In [3]:
# One cell RNN input_dim (4) -> output_dim (2)
x_data = np.array([[h]], dtype=np.float32)

hidden_size = 2
cell = tf.keras.layers.SimpleRNNCell(units=hidden_size) 
rnn = tf.keras.layers.RNN(cell, return_sequences=True, return_state=True) 
                               # return_sequences=True : 출력으로 시퀀스 전체를 출력할지 여부를 설정
outputs, states = rnn(x_data)

print('x_data: {}, shape: {}'.format(x_data, x_data.shape))
print('outputs: {}, shape: {}'.format(outputs, outputs.shape))
print('states: {}, shape: {}'.format(states, states.shape))

x_data: [[[1. 0. 0. 0.]]], shape: (1, 1, 4)
outputs: [[[-0.4360823  0.4310668]]], shape: (1, 1, 2)
states: [[-0.4360823  0.4310668]], shape: (1, 2)


In [4]:
# 위 코드와  동일한 결과
rnn = tf.keras.layers.SimpleRNN(units=hidden_size, return_sequences=True,
                       return_state=True) 

outputs, states = rnn(x_data)

print('x_data: {}, shape: {}'.format(x_data, x_data.shape))
print('outputs: {}, shape: {}'.format(outputs, outputs.shape))
print('states: {}, shape: {}'.format(states, states.shape))

x_data: [[[1. 0. 0. 0.]]], shape: (1, 1, 4)
outputs: [[[ 0.6507336  -0.68834627]]], shape: (1, 1, 2)
states: [[ 0.6507336  -0.68834627]], shape: (1, 2)


### Unfolding to n sequences

![image](https://cloud.githubusercontent.com/assets/901975/23383634/649efd0a-fd82-11e6-925d-8041242743b0.png)

In [5]:
# One cell RNN input_dim (4) -> output_dim (2). sequence: 5
x_data = np.array([[h, e, l, l, o]], dtype=np.float32)

hidden_size = 2
rnn = tf.keras.layers.SimpleRNN(units=2, return_sequences=True, return_state=True)    
outputs, states = rnn(x_data)

print('x_data: {}, shape: {} \n'.format(x_data, x_data.shape))
print('outputs: {}, shape: {} \n'.format(outputs, outputs.shape))
print('states: {}, shape: {}'.format(states, states.shape))

x_data: [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]], shape: (1, 5, 4) 

outputs: [[[-0.6814219  -0.511346  ]
  [-0.01621173  0.1252823 ]
  [-0.62091553  0.07423609]
  [-0.24643683 -0.29448262]
  [ 0.14834651 -0.60786676]]], shape: (1, 5, 2) 

states: [[ 0.14834651 -0.60786676]], shape: (1, 2)


### Batching input

![image](https://cloud.githubusercontent.com/assets/901975/23383681/9943a9fc-fd82-11e6-8121-bd187994e249.png)

In [6]:
# One cell RNN input_dim (4) -> output_dim (2). sequence: 5, batch 3
# 3 batches 'hello', 'eolll', 'lleel'
x_data = np.array([[h, e, l, l, o],
                   [e, o, l, l, l],
                   [l, l, e, e, l]], dtype=np.float32)

hidden_size = 2
rnn = tf.keras.layers.SimpleRNN(units=2, return_sequences=True, return_state=True)    
outputs, states = rnn(x_data)

print('x_data: {}, shape: {} \n'.format(x_data, x_data.shape))
print('outputs: {}, shape: {} \n'.format(outputs, outputs.shape))
print('states: {}, shape: {}'.format(states, states.shape))

x_data: [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[0. 1. 0. 0.]
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]]

 [[0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]]], shape: (3, 5, 4) 

outputs: [[[ 0.08819446  0.38960198]
  [-0.54972345 -0.25454485]
  [-0.62916857 -0.90192676]
  [-0.10827651 -0.92834145]
  [ 0.5384187   0.50896376]]

 [[-0.23865207 -0.37898633]
  [ 0.04018344  0.4654518 ]
  [-0.88012123 -0.6657547 ]
  [-0.35904893 -0.9530476 ]
  [-0.0225377  -0.8821077 ]]

 [[-0.72597563 -0.7182675 ]
  [-0.29450056 -0.93763316]
  [ 0.5699696  -0.6717871 ]
  [ 0.46014357  0.07775088]
  [-0.7337473  -0.41172546]]], shape: (3, 5, 2) 

states: [[ 0.5384187   0.50896376]
 [-0.0225377  -0.8821077 ]
 [-0.7337473  -0.41172546]], shape: (3, 2)
