In [1]:
# softmax_multi_classification
# multi-nomial Classification (다중 분류) : Y값의 범주가 3개 이상인 분류
# 활성화 함수(Activation function) 으로 softmax()가 사용 된다
# 회귀 모델(일차함수)로 가림막을 3가지 침(분류갯수=3이면)

import tensorflow as tf
import numpy as np
tf.random.set_seed(5)

In [2]:
# train data set :
# x_data :  [N,4]  --> [8,4]
x_data = [[1,2,1,1],
          [2,1,3,2],
          [3,1,3,4],
          [4,1,5,5],
          [1,7,5,5],
          [1,2,5,6],
          [1,6,6,6],
          [1,7,7,7]]

# y_data : [N,3] --> [8,3]
y_data = [[0,0,1],  # [2]
          [0,0,1],  # [2]
          [0,0,1],  # [2]
          [0,1,0],  # [1]
          [0,1,0],  # [1]
          [0,1,0],  # [1]
          [1,0,0],  # [0]
          [1,0,0]]  # [0]
# one hot 인코딩

x_train = np.array(x_data,dtype=np.float32)
y_train = np.array(y_data,dtype=np.float32)


In [3]:
# 변수 초기화 : weight, bias
# (8,3) *(4,3) = (8,3)
nb_classes = 3  # 분류 갯수

W = tf.Variable(tf.random.normal([4,nb_classes]), name ='weight')
b = tf.Variable(tf.random.normal([nb_classes]), name = 'bias')

In [4]:
# hypothesis 예측 함수 : H(X) = softmax(W*X + b)
def logits(X):
    return tf.matmul(X,W) + b

def hypothesis(X):
    return   tf.nn.softmax(logits(X))
# 위 함수 반환값을 아래 함수에서 사용

In [5]:
# # 비용 함수 구현 방법 1 : log함수를 사용하여 수식을 직접 표현
# def cost_func():
#     cost = tf.reduce_mean(-tf.reduce_sum(y_train*tf.math.log(hypothesis(x_train)),axis=1))
    
#     return cost

In [6]:
# 비용 함수 구현 방법 2 : tf.nn.softmax_cross_entropy_with_logits() 함수 사용
def cost_func():
    cost_i = tf.nn.softmax_cross_entropy_with_logits(logits=logits(x_train),
                                                     labels=y_train)
    cost = tf.reduce_mean(cost_i)
    return cost

In [7]:
# 경사 하강법
# learning_rate(학습율) 을 0.01로 설정하여 optimizer 객체를 생성
optimizer = tf.keras.optimizers.Adam(lr=0.01)

In [8]:
# 학습 시작
print('***** Start Learning!!')
for step in range(5001):
    # cost를 minimize한다
    optimizer.minimize(cost_func,var_list=[W,b])
    
    if step % 1000 == 0:
        print('%04d'%step,'cost: [',cost_func().numpy(),']',
             'W:',W.numpy(),'b:',b.numpy())

print('***** Learning Finished')

***** Start Learning!!
0000 cost: [ 5.9294786 ] W: [[-0.17030679 -0.94028634 -0.04964045]
 [-0.7325406   1.3331522  -0.628548  ]
 [ 0.86406636 -0.07899956  2.4388697 ]
 [ 0.77250797  1.2759615   0.9701489 ]] b: [0.2365285  0.8206551  0.73660946]
1000 cost: [ 0.31467578 ] W: [[-2.2194247e+00  5.2480620e-01  1.1872505e+00]
 [ 1.2104916e-01  2.2530602e-03 -6.3700572e-02]
 [ 2.2870739e+00  1.1651016e+00  6.7435086e-01]
 [ 1.2760866e+00  1.7768894e+00  3.7673813e-01]] b: [-2.71877   -1.5067686  4.317265 ]
2000 cost: [ 0.16304699 ] W: [[-3.7972443   1.3537493   2.267659  ]
 [ 0.0414911   0.02373775  0.06498498]
 [ 3.5885108   1.0490662  -0.50219786]
 [ 1.0556871   1.817029    0.5562779 ]] b: [-6.1154466 -1.3375344  7.16916  ]
3000 cost: [ 0.08965951 ] W: [[-5.2343016   2.1662533   3.2086897 ]
 [-0.04391001  0.06965797  0.16019413]
 [ 4.8728337   0.69199216 -1.5755051 ]
 [ 0.73721164  2.0572202   0.7426419 ]] b: [-9.075828  -1.3604162  9.762421 ]
4000 cost: [ 0.05118698 ] W: [[-6.569132    2.

In [9]:
# 회귀 계수 : weight과 bias출력
print('Weight :',W.numpy())
print('Bias:',b.numpy())

Weight : [[-7.8441830e+00  3.6925721e+00  4.8953791e+00]
 [-2.1366470e-01  1.7167602e-01  3.2927620e-01]
 [ 7.3285356e+00 -1.4589632e-01 -3.5808389e+00]
 [-2.5742422e-03  2.6041079e+00  1.1803545e+00]]
Bias: [-14.22404    -1.3462191  14.310619 ]


In [11]:
# 예측
# tf.argmax() : 값이 가장 큰 요소의 인덱스 값을 반환
def predict(X):
    return tf.argmax(hypothesis(X),axis=1)

print('***** Predict')

# 학습데이터를 그대로 검증데이터로 사용한 경우
x_test = np.array(x_data,dtype=np.float32)
y_test = np.array(y_data,dtype=np.float32)

preds = predict(x_test)
print(preds.numpy())
print(hypothesis(x_test).numpy())
print(tf.argmax(y_test,1).numpy())

***** Predict
[2 2 2 1 1 1 0 0]
[[6.7201891e-15 4.4788094e-06 9.9999547e-01]
 [3.0885475e-11 6.2573748e-03 9.9374264e-01]
 [8.2859493e-18 3.1583805e-02 9.6841621e-01]
 [5.7242741e-16 9.7510344e-01 2.4896599e-02]
 [5.8690630e-02 9.3963599e-01 1.6734032e-03]
 [3.0668104e-02 9.6914285e-01 1.8900630e-04]
 [9.2271829e-01 7.7280879e-02 9.1235347e-07]
 [9.9905401e-01 9.4603549e-04 1.0147023e-10]]
[2 2 2 1 1 1 0 0]
