In [1]:
import tensorflow as tf
tf.__version__

# https://www.tensorflow.org/tutorials/customization/basics?hl=ko

'2.0.0'

In [2]:
import tensorflow as tf
import numpy as np

# 상수  : tf.constant()
s = tf.constant('Hello Tensorflow!!')
print(s)

a = tf.constant([[1.0,2.0],
                 [3.0,4.0]])
b = tf.constant([[1.0,1.0],
                 [0.0,1.0]])
c = tf.matmul(a,b)   # 내적 곱셈
print(c)
type(c)

tf.Tensor(b'Hello Tensorflow!!', shape=(), dtype=string)
tf.Tensor(
[[1. 3.]
 [3. 7.]], shape=(2, 2), dtype=float32)


tensorflow.python.framework.ops.EagerTensor

In [3]:
# 변수 : tf.Variable()
# 초기값이 설정, 주로 텐서플로 내부에서 학습 연산시 변경되는 값을 저장, weight과 bias
a = tf.Variable(100)
b = tf.Variable(200)
c = tf.add(a,b)
print(c)

tf.Tensor(300, shape=(), dtype=int32)


### tf.Tensor: 텐서 객체
#### 텐서는 다차원 배열로 넘파이(NumPy) ndarray 객체와 비슷하며,
#### tf.Tensor 객체는 데이터 타입과 크기를 가지고 있다.
#### 또한 tf.Tensor는 GPU 같은 가속기 메모리에 상주할 수 있다.
#### 텐서플로는 텐서를 생성하고 이용하는 풍부한 연산 라이브러리(tf.add, tf.matmul, tf.linalg.inv 등.)를 제공하며
#### 연산수행 시 자동으로 텐서를 파이썬 네이티브(native) 타입으로 변환하여 연산한다

In [4]:
# 연산자
print(tf.add(1.,2.))  
print(tf.add([1,2],[3,4]))
print(tf.square(5))  # 제곱
print(tf.reduce_sum([1,2,3,4,5])) # 합?


tf.Tensor(3.0, shape=(), dtype=float32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(15, shape=(), dtype=int32)


In [5]:
# 속성과 타입 변환
a = tf.constant([[1.0, 2.0],
                 [3.0, 4.0]])
print(a)
print(type(a))
print(a.shape)
print(a.dtype)  # EagerTensor- 즉시 쓸 수 있는 것

# Tensor객체를 numpy ndarray로 변환
n = a.numpy()
print(n,type(n)) # <class 'numpy.ndarray'>

# 파이썬 native 타입으로 변환
a = tf.constant(10)
b = int(a)
print(b,type(b))  # 10 <class 'int'>

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>
(2, 2)
<dtype: 'float32'>
[[1. 2.]
 [3. 4.]] <class 'numpy.ndarray'>
10 <class 'int'>


In [6]:
# 1.x 구버전용 문서임
from tensorflow.python.framework.ops import Tensor, EagerTensor
print(Tensor.__doc__) # OK

Represents one of the outputs of an `Operation`.

  A `Tensor` is a symbolic handle to one of the outputs of an
  `Operation`. It does not hold the values of that operation's output,
  but instead provides a means of computing those values in a
  TensorFlow `tf.compat.v1.Session`.

  This class has two primary purposes:

  1. A `Tensor` can be passed as an input to another `Operation`.
     This builds a dataflow connection between operations, which
     enables TensorFlow to execute an entire `Graph` that represents a
     large, multi-step computation.

  2. After the graph has been launched in a session, the value of the
     `Tensor` can be computed by passing it to
     `tf.Session.run`.
     `t.eval()` is a shortcut for calling
     `tf.compat.v1.get_default_session().run(t)`.

  In the following example, `c`, `d`, and `e` are symbolic `Tensor`
  objects, whereas `result` is a numpy array that stores a concrete
  value:

  ```python
  # Build a dataflow graph.
  c = tf.constant([