### Logistic Regression : 2진 분류(Binary Classification)
: 2진 분류의 활성화 함수로는 sigmoid가 사용됨

In [1]:
import tensorflow as tf
import numpy as np
tf.random.set_seed(5)

In [2]:
# 학습용 데이터
# x_data : [6,2]
x_data = [[1,2],
          [2,3],
          [3,1],
          [4,3],
          [5,3],
          [6,2]]

# y_data : [6,1]
y_data = [[0],
          [0],
          [0],
          [1],
          [1],
          [1]]
x_train = np.array(x_data,dtype=np.float32)
y_train = np.array(y_data,dtype=np.float32)

In [3]:
# 변수 초기화 : weight, bias
# (m,n) * (n,l)  = (m,l)  , 행렬의 내적 곱셈 공식
# (6,2) * (2,1)  = (6,1)

W = tf.Variable(tf.random.normal([2,1]), name ='weight')
b = tf.Variable(tf.random.normal([1]), name = 'bias')

In [4]:
# hypothesis 예측 함수 : H(X) = sigmoid(W*X + b)
# tf.sigmoid() : tf.div(1. , 1. + tf.exp(-(tf.matmul(X,W) + b)))
def hypothesis(X):
    return   tf.sigmoid(tf.matmul(X,W) + b)  # 0 ~ 1 사이의 값을 출력

In [5]:
# 비용 함수 : logloss ,2진 분류모델
def cost_func():
    # cost = tf.reduce_mean(tf.square(hypothesis(x_train) - y_train)) #회귀모델
    cost = -tf.reduce_mean(y_train*tf.math.log(hypothesis(x_train)) +
                         (1-y_train)*tf.math.log(1-hypothesis(x_train)))
    return cost

In [6]:
# 경사 하강법
# learning_rate(학습율) 을 0.01로 설정하여 optimizer 객체를 생성
optimizer = tf.keras.optimizers.Adam(lr=0.01)

In [7]:
# 학습 시작
print('***** Start Learning!!')
for step in range(10001):
    # cost를 minimize한다
    optimizer.minimize(cost_func,var_list=[W,b])
    
    if step % 1000 == 0:
        print('%04d'%step,'cost: [',cost_func().numpy(),']',
             'W:',W.numpy(),'b:',b.numpy())

print('***** Learning Finished')

***** Start Learning!!
0000 cost: [ 1.661137 ] W: [[-0.17030667]
 [-0.9402863 ]] b: [0.23652855]
1000 cost: [ 0.17934632 ] W: [[1.3178085 ]
 [0.19723554]] b: [-4.7614303]
2000 cost: [ 0.07253334 ] W: [[2.0121026]
 [0.8405846]] b: [-8.711953]
3000 cost: [ 0.037006143 ] W: [[2.6189137]
 [1.2299305]] b: [-11.698348]
4000 cost: [ 0.020763224 ] W: [[3.170925 ]
 [1.5396553]] b: [-14.28583]
5000 cost: [ 0.012184973 ] W: [[3.6927993]
 [1.8153362]] b: [-16.680557]
6000 cost: [ 0.0073189805 ] W: [[4.1976485]
 [2.0743663]] b: [-18.97369]
7000 cost: [ 0.00445227 ] W: [[4.692671 ]
 [2.3246496]] b: [-21.210663]
8000 cost: [ 0.0027277253 ] W: [[5.1819453]
 [2.570162 ]] b: [-23.415749]
9000 cost: [ 0.0016780436 ] W: [[5.667814]
 [2.812966]] b: [-25.602295]
10000 cost: [ 0.001034755 ] W: [[6.1516347]
 [3.0542414]] b: [-27.77797]
***** Learning Finished


In [8]:
# 회귀 계수 : weight과 bias출력
print('Weight :',W.numpy())
print('Bias:',b.numpy())

Weight : [[6.1516347]
 [3.0542414]]
Bias: [-27.77797]


In [9]:
# 정확도 측정 : accuracy computation
# np.round(hypothesis(x_train).numpy())
def predict(X):
    return tf.cast(hypothesis(X)>0.5,dtype=tf.float32 ) # 타입 변환함수 사용

# 학습데이터를 그대로 검증데이터로 사용하여 예측한 경우
x_test = x_train
y_test = y_train

preds = predict(x_test)  
accuarcy = tf.reduce_mean(tf.cast(tf.equal(preds,y_test),dtype=tf.float32))

print('Accuracy:',accuarcy.numpy())
print('Hypothesis:\n',hypothesis(x_test).numpy())
print('Predict:\n',preds.numpy())

Accuracy: 1.0
Hypothesis:
 [[1.8225627e-07]
 [1.8111591e-03]
 [1.8908737e-03]
 [9.9750584e-01]
 [9.9999464e-01]
 [9.9999976e-01]]
Predict:
 [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]]


In [10]:
# 예측
print('***** Predict')
# x_data = [[1,2],
#           [2,3],
#           [3,1],
#           [4,3],
#           [5,3],
#           [6,2]]
x_data = [[1,1],
          [2,5],
          [3,2],
          [4,4],
          [5,2],
          [6,6]]
x_test = np.array(x_data,dtype=np.float32)
preds = predict(x_test)
print(preds.numpy())

***** Predict
[[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]]
