### * RNN 주요 레이어 종류
#### (1) SimpleRNN :가장 간단한 형태의 RNN레이어, 활성화 함수로 tanh가 사용됨(tanh: -1 ~ 1 사이의 값을 반환)
#### (2) LSTM(Long short Term Memory) : 입력 데이터와 출력 사이의 거리가 멀어질수로 연관 관계가 적어진다(Long Term Dependency,장기의존성 문제), LSTM은 장기 의존성 문제를 해결하기 위해 출력값외에 셀상태(cell state)값을 출력함, 활 함수로 tanh외에 sigmoid가 사용됨
#### (3) GRU(Gated Recurent Unit) : 뉴욕대 조경현 교수 등이 제안, LSTM보다 구조가 간단하고 성능이 우수함

In [1]:
# rnn_basic

import tensorflow as tf
import numpy as np


In [2]:
# Sequence data
X = np.array([[0,1,2,3],
              [1,2,3,4],
              [2,3,4,5],
              [3,4,5,6],
              [4,5,6,7],
              [5,6,7,8]],dtype=np.float32)

x_data = tf.reshape(X,(-1,4,1))  # (6,4,1)

y_data = np.array([4,5,6,7,8,9],dtype=np.float32)

print(x_data.shape,y_data.shape)
# print(type(x_data),type(y_data))
x_data

(6, 4, 1) (6,)


<tf.Tensor: id=2, shape=(6, 4, 1), dtype=float32, numpy=
array([[[0.],
        [1.],
        [2.],
        [3.]],

       [[1.],
        [2.],
        [3.],
        [4.]],

       [[2.],
        [3.],
        [4.],
        [5.]],

       [[3.],
        [4.],
        [5.],
        [6.]],

       [[4.],
        [5.],
        [6.],
        [7.]],

       [[5.],
        [6.],
        [7.],
        [8.]]], dtype=float32)>

### [1] SimpleRNN
#### 가장 간단한 형태의 RNN 

In [3]:
# RNN 순환 신경망 구현  : SimpleRNN
model = tf.keras.Sequential([
    tf.keras.layers.SimpleRNN(units=300, return_sequences=True, input_shape=[4,1]),
    tf.keras.layers.SimpleRNN(units=300),
    tf.keras.layers.Dense(1)
])

model.compile(optimizer='adam', loss='mse')
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn (SimpleRNN)       (None, 4, 300)            90600     
_________________________________________________________________
simple_rnn_1 (SimpleRNN)     (None, 300)               180300    
_________________________________________________________________
dense (Dense)                (None, 1)                 301       
Total params: 271,201
Trainable params: 271,201
Non-trainable params: 0
_________________________________________________________________


In [4]:
# 학습 및 예측
model.fit(x_data, y_data, epochs=100, verbose=1)
print(model.predict(x_data))

Train on 6 samples
Epoch 1/100
6/6 [==============================] - 1s 209ms/sample - loss: 44.9459
Epoch 2/100
6/6 [==============================] - 0s 665us/sample - loss: 1.1576
Epoch 3/100
6/6 [==============================] - 0s 831us/sample - loss: 5.6705
Epoch 4/100
6/6 [==============================] - 0s 1ms/sample - loss: 6.8891
Epoch 5/100
6/6 [==============================] - 0s 833us/sample - loss: 3.2733
Epoch 6/100
6/6 [==============================] - 0s 824us/sample - loss: 1.2980
Epoch 7/100
6/6 [==============================] - 0s 830us/sample - loss: 2.8860
Epoch 8/100
6/6 [==============================] - 0s 665us/sample - loss: 3.6655
Epoch 9/100
6/6 [==============================] - 0s 831us/sample - loss: 2.4104
Epoch 10/100
6/6 [==============================] - 0s 824us/sample - loss: 1.1509
Epoch 11/100
6/6 [==============================] - 0s 665us/sample - loss: 0.8247
Epoch 12/100
6/6 [==============================] - 0s 836us/sample - loss: 1.

Epoch 100/100
6/6 [==============================] - 0s 831us/sample - loss: 0.0052
[[4.0171146]
 [4.9585853]
 [5.9892755]
 [7.0860286]
 [8.078407 ]
 [8.883277 ]]


In [5]:
# 학습되지 않은 입력 데이터에 대한 예측 결과
print(model.predict(np.array([[[6.],[7.],[8.],[9.]]])))
print(model.predict(np.array([[[-1.],[0.],[1.],[2.]]])))

[[9.489812]]
[[1.1841613]]


In [6]:
model.evaluate(x_data, y_data)

6/1 [====================================================================================================================================================================================] - 0s 28ms/sample - loss: 0.0049


0.004882666748017073

### [2] LSTM(Long short Term Memory)
#### 입력 데이터와 출력 사이의 거리가 멀어질수로 연관 관계가 적어진다(Long Term Dependency,장기의존성 문제)
#### LSTM은 장기 의존성 문제를 해결하기 위해 출력값외에 셀상태(cell state)값을 출력함

In [7]:
# RNN 순환 신경망 구현  : LSTM
model = tf.keras.Sequential([
    tf.keras.layers.LSTM(units=300, return_sequences=True, input_shape=[4,1]),
    tf.keras.layers.LSTM(units=300),
    tf.keras.layers.Dense(1)
])

model.compile(optimizer='adam', loss='mse')
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm (LSTM)                  (None, 4, 300)            362400    
_________________________________________________________________
lstm_1 (LSTM)                (None, 300)               721200    
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 301       
Total params: 1,083,901
Trainable params: 1,083,901
Non-trainable params: 0
_________________________________________________________________


In [8]:
# 학습 및 예측
model.fit(x_data, y_data, epochs=100, verbose=0)
print(model.predict(x_data))

[[3.36867  ]
 [5.084898 ]
 [6.3646984]
 [7.3020678]
 [7.9971433]
 [8.522389 ]]


In [9]:
# 학습되지 않은 입력 데이터에 대한 예측 결과
print(model.predict(np.array([[[6.],[7.],[8.],[9.]]])))
print(model.predict(np.array([[[-1.],[0.],[1.],[2.]]])))

[[8.926542]]
[[1.2625331]]


### [3] GRU(Gated Recurent Unit)
#### 뉴욕대 조경현 교수 등이 제안, LSTM보다 구조가 간단하고 성능이 우수

In [10]:
# RNN 순환 신경망 구현  : GRU
model = tf.keras.Sequential([
    tf.keras.layers.GRU(units=300, return_sequences=True, input_shape=[4,1]),
    tf.keras.layers.GRU(units=300),
    tf.keras.layers.Dense(1)
])

model.compile(optimizer='adam', loss='mse')
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
gru (GRU)                    (None, 4, 300)            272700    
_________________________________________________________________
gru_1 (GRU)                  (None, 300)               541800    
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 301       
Total params: 814,801
Trainable params: 814,801
Non-trainable params: 0
_________________________________________________________________


In [11]:
# 학습 및 예측
model.fit(x_data, y_data, epochs=100, verbose=0)
print(model.predict(x_data))

[[3.6361449]
 [5.0235453]
 [6.21258  ]
 [7.208928 ]
 [8.031518 ]
 [8.704548 ]]


In [12]:
# 학습되지 않은 입력 데이터에 대한 예측 결과
print(model.predict(np.array([[[6.],[7.],[8.],[9.]]])))
print(model.predict(np.array([[[-1.],[0.],[1.],[2.]]])))

[[9.252574]]
[[2.0685813]]


In [13]:
# RNN 사용 단어 학습 예측

In [14]:
# idx2char = ['h','i','e','l','o'] # 문자를 인덱스로 접근 가능
idx2char = ['a','b','c','d','e','f','g'] # 문자를 인덱스로 접근 가능

# x_data = np.array([0,1,0,2,3,3]) # 'hihell', (6,)
# y_data = np.array([1,0,2,3,3,4]) # 'ihello'  (6,)

x_data = np.array([[0,1,2,3,4,5]]) # 'abcdef', (1,6)
y_data = np.array([[1,2,3,4,5,6]]) # 'bcdefg'  (1,6)

x_one_hot = tf.one_hot(x_data,6)  # (6,6)
x_data = tf.reshape(x_one_hot,(-1,6,6))  # (1,6,6)
print(x_data.shape)
print(x_data)

(1, 6, 6)
tf.Tensor(
[[[1. 0. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 1.]]], shape=(1, 6, 6), dtype=float32)


In [15]:
model = tf.keras.Sequential([
#     tf.keras.layers.SimpleRNN(units=30, return_sequences=True, input_shape=[5,1]),
#     tf.keras.layers.SimpleRNN(units=30),
#     tf.keras.layers.LSTM(units=30, return_sequences=True, input_shape=[5,1]),
#     tf.keras.layers.LSTM(units=30),
    tf.keras.layers.LSTM(units=1024, return_sequences=True, input_shape=[6,6]),
    tf.keras.layers.LSTM(units=512, return_sequences=True),
    tf.keras.layers.LSTM(units=512, return_sequences=True),
    tf.keras.layers.LSTM(units=256, return_sequences=True),
    tf.keras.layers.LSTM(units=256, return_sequences=True),
    tf.keras.layers.LSTM(units=128, return_sequences=True),
    tf.keras.layers.LSTM(units=128, return_sequences=True),
    tf.keras.layers.LSTM(units=64, return_sequences=True),
    tf.keras.layers.LSTM(units=64, return_sequences=True),
    tf.keras.layers.LSTM(units=32, return_sequences=True),
    tf.keras.layers.LSTM(units=32),
    tf.keras.layers.Dense(6)
])

model.compile(optimizer='adam', loss='mse',metrics=['accuracy'])
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_2 (LSTM)                (None, 6, 1024)           4222976   
_________________________________________________________________
lstm_3 (LSTM)                (None, 6, 512)            3147776   
_________________________________________________________________
lstm_4 (LSTM)                (None, 6, 512)            2099200   
_________________________________________________________________
lstm_5 (LSTM)                (None, 6, 256)            787456    
_________________________________________________________________
lstm_6 (LSTM)                (None, 6, 256)            525312    
_________________________________________________________________
lstm_7 (LSTM)                (None, 6, 128)            197120    
_________________________________________________________________
lstm_8 (LSTM)                (None, 6, 128)           

In [16]:
# 학습 및 예측
model.fit(x_data, y_data, epochs=100, verbose=0)

In [17]:
pred = model.predict(x_data).astype(np.int32)
print(pred)

[[1 2 2 4 4 5]]


In [18]:
x_data,y_data

(<tf.Tensor: id=19355, shape=(1, 6, 6), dtype=float32, numpy=
 array([[[1., 0., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0., 0.],
         [0., 0., 1., 0., 0., 0.],
         [0., 0., 0., 1., 0., 0.],
         [0., 0., 0., 0., 1., 0.],
         [0., 0., 0., 0., 0., 1.]]], dtype=float32)>,
 array([[1, 2, 3, 4, 5, 6]]))