### multi-variable Linear Regression : 다항 회귀

In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

tf.random.set_seed(5)

# 학습 데이터 : X,Y
x_data = [[73.,80.,75.],
          [93.,88.,93.],
          [89.,91.,90.],
          [96.,98.,100.],
          [73.,66.,70.]]

y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]

x_train = np.array(x_data,dtype=np.float32)  
y_train = np.array(y_data,dtype=np.float32)
x_train.shape,y_train.shape

((5, 3), (5, 1))

In [2]:
# 변수 초기화 : weight, bias
# (m,n) * (n,l)  = (m,l)  , 행렬의 내적 곱셈 공식
# (5,3) * (3,1)  = (5,1)

W = tf.Variable(tf.random.normal([3,1]), name ='weight')
b = tf.Variable(tf.random.normal([1]), name = 'bias')
W

<tf.Variable 'weight:0' shape=(3, 1) dtype=float32, numpy=
array([[-0.18030666],
       [-0.95028627],
       [-0.03964049]], dtype=float32)>

In [3]:
# hypothesis 예측 함수 : H(X1,X2,X3) = W1*X1 + W2*X2 + W3*X3 + b
def hypothesis(X):
    return   tf.matmul(X,W) + b

In [4]:
# 비용 함수 : (Hx - y)^2 의 평균
# tf.square() : 제곱
# tf.reduce_mean() : 합의 평균
def cost_func():
    cost = tf.reduce_mean(tf.square(hypothesis(x_train) - y_train))
    return cost

In [5]:
# 경사 하강법
# learning_rate(학습율) 을 0.01로 설정하여 optimizer 객체를 생성
# optimizer = tf.compat.v1.train.GradientDescentOptimizer(learning_rate=0.01)
# optimizer = tf.compat.v1.train.AdamOptimizer(learning_rate=0.01)
optimizer = tf.keras.optimizers.Adam(lr=0.01)

In [6]:
# 학습 시작
print('***** Start Learning!!')
for step in range(10001):
    # cost를 minimize한다
    optimizer.minimize(cost_func,var_list=[W,b])
    
    if step % 100 == 0:
        print('%04d'%step,'cost: [',cost_func().numpy(),']',
             'W:',W.numpy(),'b:',b.numpy())

print('***** Learning Finished')

***** Start Learning!!
0000 cost: [ 72495.52 ] W: [[-0.17030665]
 [-0.9402863 ]
 [-0.02964049]] b: [0.23652864]
0100 cost: [ 4484.4697 ] W: [[ 0.6139679 ]
 [-0.15593217]
 [ 0.754649  ]] b: [1.0209028]
0200 cost: [ 39.03132 ] W: [[0.8497376 ]
 [0.08022431]
 [0.99049103]] b: [1.2571563]
0300 cost: [ 1.8185713 ] W: [[0.8725854 ]
 [0.10369529]
 [1.0134547 ]] b: [1.2807844]
0400 cost: [ 1.7926762 ] W: [[0.872841  ]
 [0.10471869]
 [1.0138539 ]] b: [1.2820021]
0500 cost: [ 1.7869017 ] W: [[0.8724857 ]
 [0.10525568]
 [1.0136645 ]] b: [1.2827668]
0600 cost: [ 1.780385 ] W: [[0.87208366]
 [0.10586476]
 [1.0134504 ]] b: [1.2836363]
0700 cost: [ 1.7731373 ] W: [[0.87163574]
 [0.1065436 ]
 [1.0132116 ]] b: [1.2846082]
0800 cost: [ 1.7651775 ] W: [[0.8711428 ]
 [0.10729134]
 [1.0129483 ]] b: [1.2856818]
0900 cost: [ 1.7565353 ] W: [[0.87060463]
 [0.10810767]
 [1.0126605 ]] b: [1.2868583]
1000 cost: [ 1.7471693 ] W: [[0.8700216 ]
 [0.10899291]
 [1.0123482 ]] b: [1.2881386]
1100 cost: [ 1.7370999 ] W:

9500 cost: [ 0.15040575 ] W: [[0.7762509 ]
 [0.39355597]
 [0.80348957]] b: [3.0747292]
9600 cost: [ 0.14542289 ] W: [[0.7786646 ]
 [0.39509755]
 [0.79896426]] b: [3.1283932]
9700 cost: [ 0.14076935 ] W: [[0.78107023]
 [0.39659917]
 [0.794491  ]] b: [3.1816597]
9800 cost: [ 0.13645592 ] W: [[0.7834555 ]
 [0.39806178]
 [0.7900828 ]] b: [3.2343774]
9900 cost: [ 0.13246866 ] W: [[0.7858089 ]
 [0.39948562]
 [0.78575236]] b: [3.2863927]
10000 cost: [ 0.12882271 ] W: [[0.78812015]
 [0.40086982]
 [0.7815125 ]] b: [3.3375518]
***** Learning Finished


In [7]:
# 회귀 계수 : weight과 bias출력
print('Weight :',W.numpy())
print('Bias:',b.numpy())

Weight : [[0.78812015]
 [0.40086982]
 [0.7815125 ]]
Bias: [3.3375518]


In [8]:
# 예측
print('***** Predict')
x_data = [[73.,80.,75.],
          [93.,88.,93.],
          [89.,91.,90.],
          [96.,98.,100.],
          [73.,66.,70.]]
x_test = np.array(x_data,dtype=np.float32)
print(hypothesis(x_test).numpy())
# [[151.55334]
#  [184.58994]
#  [180.29553]
#  [196.43358]
#  [142.03362]]

# y_data = [[152.],
#           [185.],
#           [180.],
#           [196.],
#           [142.]]

***** Predict
[[151.55334]
 [184.58994]
 [180.29553]
 [196.43358]
 [142.03362]]
